
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY"
export const REMOVE_PRODUCT_QUANTITY = "REMOVE_PRODUCT_QUANTITY" 
export const EMPTY_PRODUCT_CART = "EMPTY_PRODUCT_CART"
export const CART_ADD_DELAY = "CART_ADD_DELAY"
export const CART_DELETE_DELAY = "CART_ADD_DELETE_DELAY"

